### ISSUE TITLE
Head request returns nothing (S3)

### ISSUE THREAD

**Issue by mdchaney** [rightscale/right_aws_api#16]
I'm assuming that all API requests return the body.

Trying a simple example of putting a new object and then using "head" returns an empty string.  I can "get" just fine, but "head" is always empty.

2.1.5 :040 > RIGHT_AWS_S3.put('test-bucket/test.txt', body: 'This is my text', headers: { 'content-type' => 'text/plain', 'x-amz-meta-hello' => 'hello' })
2.1.5 :041 > RIGHT_AWS_S3.get('test-bucket/test.txt')
 => "This is my text" 
2.1.5 :042 > RIGHT_AWS_S3.head('test-bucket/test.txt')
 => "" 

Using the old aws-s3 gem:

>> o=S3Object.find('test.txt','test-bucket')
=> #<AWS::S3::S3Object:0x70181021360560 '/test-bucket/test.txt'>
>> pp o.about
{"x-amz-id-2"=>
  "siTHRRTCaFkEuxqLIkQ9caa8gHJ/18R8gV0SxYSATXod+mzltWA3dBZUl0zGto4C",
 "x-amz-request-id"=>"1DD601B0FC0DDEA2",
 "date"=>"Wed, 14 Jan 2015 22:14:38 GMT",
 "last-modified"=>"Wed, 14 Jan 2015 21:42:53 GMT",
 "etag"=>"\"088b19be96ab393523e1553cf8e871e4\"",
 "accept-ranges"=>"bytes",
 "content-type"=>"text/plain",
 "content-length"=>"15",
 "server"=>"AmazonS3"}
=> {"x-amz-id-2"=>"siTHRRTCaFkEuxqLIkQ9caa8gHJ/18R8gV0SxYSATXod+mzltWA3dBZUl0zGto4C", "x-amz-request-id"=>"1DD601B0FC0DDEA2", "date"=>"Wed, 14 Jan 2015 22:14:38 GMT", "last-modified"=>"Wed, 14 Jan 2015 21:42:53 GMT", "etag"=>"\"088b19be96ab393523e1553cf8e871e4\"", "accept-ranges"=>"bytes", "content-type"=>"text/plain", "content-length"=>"15", "server"=>"AmazonS3"}
>> pp o.metadata
{"x-amz-meta-hello"=>"hello"}
=> {"x-amz-meta-hello"=>"hello"}

Back to right_aws_api:

2.1.5 :043 > RIGHT_AWS_S3.ListObjects('Bucket' => 'test-bucket', prefix: 'test' )
 => {"ListBucketResult"=>{"@xmlns"=>"http://s3.amazonaws.com/doc/2006-03-01/", "Name"=>"test-bucket", "Prefix"=>"test", "Marker"=>nil, "MaxKeys"=>"1000", "IsTruncated"=>"false", "Contents"=>{"Key"=>"test.txt", "LastModified"=>"2015-01-14T21:42:53.000Z", "ETag"=>"\"088b19be96ab393523e2553cf8e871e4\"", "Size"=>"15", "Owner"=>{"ID"=>"9fdbc1694174cebf7937e642dc933cbbe79b2106d8e3f394028334204e599fe5", "DisplayName"=>"mdchaney"}, "StorageClass"=>"STANDARD"}}} 
2.1.5 :044 > info = RIGHT_AWS_S3.get('test-bucket', params: { prefix: 'test' })
 => {"ListBucketResult"=>{"@xmlns"=>"http://s3.amazonaws.com/doc/2006-03-01/", "Name"=>"test-bucket", "Prefix"=>"test", "Marker"=>nil, "MaxKeys"=>"1000", "IsTruncated"=>"false", "Contents"=>{"Key"=>"test.txt", "LastModified"=>"2015-01-14T21:42:53.000Z", "ETag"=>"\"088b19be96ab393523e2553cf8e871e4\"", "Size"=>"15", "Owner"=>{"ID"=>"9fdbc1694174cebf7937e642dc933cbbe79b2106d8e3f394028334204e599fe5", "DisplayName"=>"mdchaney"}, "StorageClass"=>"STANDARD"}}} 
2.1.5 :045 > RIGHT_AWS_S3.delete('test-bucket/test.txt')
 => "" 
2.1.5 :046 > RIGHT_AWS_S3.get('test-bucket/test.txt')
RightScale::CloudApi::HttpError: 404: NoSuchKey: The specified key does not exist. (RequestID: 8E040184850CD732)

So it's there, I can do everything, but I can't get to the headers.

Any help is appreciated.  I really like this interface and the fact that it can be used in a threaded environment.

**Comment by konstantin-dzreyev** [comment]
In this gem we do as less post processing as possible so there is no any spectial ruby method that returns you S3 HEAD data. But you can easily get it from the response headers. Everything that starts with 'x-amz-meta-' is the data you are looking for:

```ruby
# put +set metadata
pp s3.put('a.b.c.d.1.com/11',
  :body => '333',
  :headers => {
    'x-amz-meta-foo' => 'bar'
  }
)
# get metadata
pp s3.head('a.b.c.d.1.com/11').metadata[:headers] #=> 
  {:headers=>
    {"x-amz-id-2"=>
      ["sdfsafa...0="],
     "x-amz-request-id"=>["5A94CDD755F2F81C"],
     "date"=>["Sat, 17 Jan 2015 05:34:54 GMT"],
     "x-amz-meta-foo"=>["bar"],
     "last-modified"=>["Sat, 17 Jan 2015 05:34:54 GMT"],
     "etag"=>["\"310dcbbf4cce62f762a2aaa148d556bd\""],
     "accept-ranges"=>["bytes"],
     "content-type"=>["application/octet-stream"],
     "content-length"=>["3"],
     "server"=>["AmazonS3"]},
   :code=>"200"}


```

**Comment by mdchaney** [comment]
Note that searching for "metadata" in the documentation returns nothing.  The "issue" here, then, is that the "metadata" - and whatever the http response code method is - are undocumented.

**Comment by konstantin-dzreyev** [comment]
Right, docs are not complete yet. Sorry for that. I'll add a story for this.

**Comment by mdchaney** [comment]
Thank you!
