### ISSUE TITLE
HostedZoneId duplication

### ISSUE THREAD

**Issue by superspring** [rightscale/right_aws_api#23]
Hey,

Looking at this code, it looks as if the 'HostedZoneId' variable is being used twice for two different operations.

https://github.com/rightscale/right_aws_api/blob/master/lib/cloud/aws/route53/wrappers/default.rb#L97

On line 84, I can pass 'HostedZoneId' as the hosted zone to do the operation on, but the same variable is used again on line 97 as the alias, which may be a different zone, or not required at all.

Is this an issue or am I incorrectly interfacing with this code?

**Comment by konstantin-dzreev** [comment]
It seems that you are right. It should be
'HostedZoneId' => :TargetHostedZoneId

I'll fix it, thanks

**Comment by superspring** [comment]
Thanks for this fix. Do you also need to set the default for 'TargetHostedZoneId', otherwise the function can't be called without?

Also, when will this be available as a ruby gem?

**Comment by konstantin-dzreev** [comment]
yep, right. I also noticed that CreateHostedZone**s** should actually be names as CreateHostedZone.

And there is a new API version already "2013-04-01"... Do you mind if I add all these new features and ask you to review the pull request  before I merge it to master?

P.S. It may take couple days for me to get it ready

**Comment by superspring** [comment]
That sounds fine, let me know when it's ready.

**Comment by konstantin-dzreev** [comment]
It took a while, but here it is: https://github.com/rightscale/right_aws_api/pull/25/files.
I'd apperciate it you would pull that branch up and played with both Route53 and Route53 Domain api

Thanks

**Comment by konstantin-dzreev** [comment]
P.S. plz skip ruby code but check if API params and methods definitions look good

**Comment by konstantin-dzreev** [comment]
Hi there!
Did you have a chance to play with it?

**Comment by superspring** [comment]
Hey, sorry for my late reply.

The only issues that I could find with this are:
* It doesn't accept a host without a region, such as 'route53.amazonaws.com'
** https://gist.github.com/superspring/695dbca6618c4269f968
* ...and the schema you're using is still the really old one
** https://gist.github.com/superspring/f19568e35968ed3ed058

Besides that, it's tested on a production system and working well :)

**Comment by konstantin-dzreev** [comment]
Thanks! Updated.

Could you give it a final look before I merge?

**Comment by konstantin-dzreev** [comment]
Merged
