### ISSUE TITLE
Cannot do block-based chunk gets on S3

### ISSUE THREAD

**Issue by mdchaney** [rightscale/right_aws_api#24]
Using simple code:

require 'right_aws_api'
bucket_name = 'bucketname'
AMAZON_ACCESS_KEY_ID = 'key'
AMAZON_SECRET_ACCESS_KEY = 'key'
2.2-head :005 > s3_connection = RightScale::CloudApi::AWS::S3::Manager.new(
2.2-head :006 >       AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_ACCESS_KEY, "http://s3.amazonaws.com/"
2.2-head :007?>   )
 => #<RightScale::CloudApi::AWS::S3::Manager:0x007fe0d342eeb8 @block=nil, @args= ["", "", ""]
, @api_manager_class=RightScale::CloudApi::AWS::S3::ApiManager, @api_manager_storage={}> 
2.2-head :008 > object_name = 'mas.4.1.128k.mp3'
 => "mas.4.1.128k.mp3" 
2.2-head :009 > File.open('/dev/null','w') do |file|
2.2-head :010 >     s3_connection.get("#{bucket_name}/#{object_name}") do |chunk|
2.2-head :011 >       file.write chunk
2.2-head :012?>     end
2.2-head :013?>   end

RightScale::CloudApi::ConnectionError: too many connection resets (due to Net::HTTPOK#read_body called twice - IOError) after 0 requests on 70301792891900, last used 1426105325.230732 seconds ago
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/routines/connection_proxies/net_http_persistent_proxy.rb:66:in `rescue in request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/routines/connection_proxies/net_http_persistent_proxy.rb:69:in `request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/routines/connection_proxy.rb:60:in `block in process'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/routines/routine.rb:79:in `call'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/routines/routine.rb:79:in `with_timer'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/routines/connection_proxy.rb:59:in `process'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/api_manager.rb:341:in `block (2 levels) in process_api_request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/api_manager.rb:328:in `each'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/api_manager.rb:328:in `block in process_api_request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/api_manager.rb:321:in `loop'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/api_manager.rb:321:in `process_api_request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_aws_api-0.2.3/lib/cloud/aws/s3/manager.rb:403:in `api'
	from (eval):2:in `get'
	from /Users/mdchaney/.rvm/gems/ruby-2.2-head/gems/right_cloud_api_base-0.2.1/lib/base/manager.rb:117:in `method_missing'
	from (irb):10:in `block in irb_binding'
	from (irb):9:in `open'
	from (irb):9
	from /Users/mdchaney/.rvm/rubies/ruby-2.2-head/bin/irb:11:in `<main>'2.2-head :014 >

This works fine:
response = s3_connection.get("#{bucket_name}/#{object_name}")

Am I doing something wrong?  Based on this example:

    # Download into IO object
    File.open('/tmp/boot.jpg','w') do |file|
      s3.get('devs-us-east/kd/boot.jpg') do |chunk|
        file.write(chunk)
      end
    end

Thanks.

**Comment by konstantin-dzreev** [comment]
Confirmed. Looking into it....

**Comment by konstantin-dzreev** [comment]
I believe I fixed this. The issue was in the dependency gem.

Plz try this setting in your gem:

gem 'right_cloud_api_base', git: 'git@github.com:rightscale/right_cloud_api_base.git', branch: 'S3_block_read_issue'

If it works fine I'll merge it

**Comment by mdchaney** [comment]
Seems to work fine.  I have it in production now to test it (after hours) and it's working well.

**Comment by konstantin-dzreev** [comment]
I just released a fixed version of right_cloud_api_base gem (v2.2.0), so it shold be fixed now
