### ISSUE TITLE
Incorrect documentation regarding "no_dns_buckets" option for S3

### ISSUE THREAD

**Issue by mdchaney** [rightscale/right_aws_api#33]
In lib/cloud/aws/s3/manager.rb on line 330 we're given the example:

    link = RightScale::CloudApi::AWS::S3::Link::Manager::new(key, secret, endpoint, :no_dns_buckets => true)

It should be:

    link = RightScale::CloudApi::AWS::S3::Link::Manager::new(key, secret, endpoint, :cloud => { :no_dns_buckets => true })

**Comment by konstantin-dzreev** [comment]
I'll fix it, thanks

**Comment by konstantin-dzreev** [comment]
fixed
