### ISSUE TITLE
ERROR endpoint for ec2

### ISSUE THREAD

**Issue by ioricloud** [rightscale/right_aws_api#42]
I try connect in ec2 services but in my shell appears this error

shell: Credential :aws_access_key_id cannot be empty (RightScale::CloudApi::ApiManager::Error)

code: endpoint = 'https://ec2.sa-east-1.amazonaws.com/'

**Comment by konstantin-dzreev** [comment]
It seems that you are sending an empty aws access key is.

```
  key      = 'your aws access key id'
  secret   = 'your aws secret access key'
  endpoint = 'https://ec2.sa-east-1.amazonaws.com'
  ec2      = RightScale::CloudApi::AWS::EC2::Manager.new(key, secret, endpoint)
  ec2.DescribeInstances
```

**Comment by ioricloud** [comment]
no, I am using now my key and secret.

**Comment by konstantin-dzreev** [comment]
try this code:
```
key      = 'foo'
secret   = 'bar'
endpoint = 'https://ec2.sa-east-1.amazonaws.com'
ec2      = RightScale::CloudApi::AWS::EC2::Manager.new(key, secret, endpoint)
ec2.DescribeInstances
```
If everything is OK then you will get:
```
RightScale::CloudApi::HttpError: 401: AuthFailure: AWS was not able to validate the provided access credentials (RequestID: a80be9f9-c2a5-4085-b9f3-4bd31cab9c64)
```

Just provide it with your real keys and it will work.

**Comment by ioricloud** [comment]
Thanks konstantin

I was using with ENV in key and secret.

sorry

**Comment by konstantin-dzreev** [comment]
Glad it worked for you.
Please, close the issue.

**Comment by ioricloud** [comment]
Konstantin

I run file.rb in my shell but dont show nothing

**Comment by konstantin-dzreev** [comment]
Sorry, what's in your file.rb (plz hide your secrets)?

**Comment by ioricloud** [comment]
require 'right_aws_api'

key      = 'xx'
secret   = 'xx'
endpoint = 'https://ec2.sa-east-1.amazonaws.com/'
ec2      = RightScale::CloudApi::AWS::EC2::Manager.new(key, secret, endpoint)

ec2.DescribeInstances

ec2.DescribeInstances('InstanceId' => "i-0d304b024bd7e11cc")

**Comment by konstantin-dzreev** [comment]
if you want any output you have to use 'puts':
```
puts ec2.DescribeInstances('InstanceId' => "i-0d304b024bd7e11cc")
```
But this has nothing to do with the gem - it is just basic ruby knowledge

**Comment by ioricloud** [comment]
method_missing': undefined method `to_ary' for #<Hash:0x000000023dd770> (NoMethodError)
Did you mean?  to_a

**Comment by konstantin-dzreev** [comment]
1. What ruby version are you using?
2. Can you post the full call stack?

**Comment by ioricloud** [comment]
ok
ruby version 2.3.3 via rvm

ruby service2.rb 
/home/henrique/.rvm/gems/ruby-2.3.3/gems/right_cloud_api_base-0.2.6/lib/base/routines/result_wrapper.rb:57:in `method_missing': undefined method `to_ary' for #<Hash:0x000000023dd770> (NoMethodError)
Did you mean?  to_a
	from service2.rb:7:in `puts'
	from service2.rb:7:in `puts'
	from service2.rb:7:in `<main>'
henrique@thor:~/AulasDocker/aws/testrails$

**Comment by konstantin-dzreev** [comment]
There is no any 'to_ary' in the gom code.
Are you doing
```
puts ec2.DescribeInstances('InstanceId' => "i-0d304b024bd7e11cc")
```
or
```
puts ec2.DescribeInstances('InstanceId' => "i-0d304b024bd7e11cc").to_ary
```
in your script?

The former should work work, the later must fail

**Comment by ioricloud** [comment]
without method

without .to_ary

**Comment by konstantin-dzreev** [comment]
Post your current script once again plz (remove secrets)

**Comment by ioricloud** [comment]
runned now with to_a method.

**Comment by konstantin-dzreev** [comment]
Wait, you just said you did not do ```to_ary```, and now you are saying you are replacing it with ```to_a```...

**Comment by ioricloud** [comment]
yes

**Comment by ioricloud** [comment]
I used to_a method for test and worked
